import type { Worker } from './Worker'
export const WorkerList: Worker[] = [
  { id: 1, city_id: 1, department_id: 1, name: 'Иванов' },
  { id: 2, city_id: 1, department_id: 1, name: 'Васильев' },
  { id: 3, city_id: 1, department_id: 1, name: 'Максимов' },
  { id: 4, city_id: 1, department_id: 2, name: 'Иванова' },
  { id: 5, city_id: 1, department_id: 2, name: 'Попов' },
  { id: 6, city_id: 1, department_id: 2, name: 'Лисицын' },
  { id: 7, city_id: 1, department_id: 3, name: 'Романов' },
  { id: 8, city_id: 1, department_id: 3, name: 'Горин' },
  { id: 9, city_id: 1, department_id: 3, name: 'Стругацкий' },
  { id: 10, city_id: 2, department_id: 4, name: 'Овечкин' },
  { id: 11, city_id: 2, department_id: 4, name: 'Вахрушин' },
  { id: 12, city_id: 2, department_id: 4, name: 'Бельченко' },
  { id: 13, city_id: 2, department_id: 5, name: 'Пешкин' },
  { id: 14, city_id: 2, department_id: 5, name: 'Чернов' },
  { id: 15, city_id: 2, department_id: 5, name: 'Липов' },
  { id: 16, city_id: 2, department_id: 6, name: 'Зуев' },
  { id: 17, city_id: 2, department_id: 6, name: 'Ленин' },
  { id: 18, city_id: 2, department_id: 6, name: 'Есенин' },
  { id: 19, city_id: 2, department_id: 6, name: 'Толстой' },
  { id: 20, city_id: 3, department_id: 7, name: 'Булгаков' },
  { id: 21, city_id: 3, department_id: 7, name: 'Работник 1' },
  { id: 22, city_id: 3, department_id: 7, name: 'Работник 2' },
  { id: 23, city_id: 3, department_id: 8, name: 'Работник 3' },
  { id: 24, city_id: 3, department_id: 8, name: 'Работник 4' },
  { id: 25, city_id: 3, department_id: 8, name: 'Работник 5' },
  { id: 26, city_id: 3, department_id: 9, name: 'Работник 6' },
  { id: 27, city_id: 3, department_id: 9, name: 'Работник 7' },
  { id: 28, city_id: 3, department_id: 9, name: 'Работник 8' },
  { id: 29, city_id: 1, department_id: 1, name: 'Работник 9' },
  { id: 30, city_id: 1, department_id: 2, name: 'Работник 10' },
]
